package com.src.printing.office.enums;

public enum ApiErrorMessage {
	NOT_FOUND, MANDATORY, DEFAULT_ERROR, VALIDATION, EXISTS, FINISHED_PRODUCTS_NOT_ENOUGH, MATERIAL_NOT_ENOUGH,
	RECEIPT_TYPE_DONT_EXISTS
}
